import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs';
import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';

import { api } from 'y/utils/api';

const Home: NextPage = () => {
	const { isSignedIn, user } = useUser();
	const { data, isLoading: isPostsLoading } = api.posts.getAll.useQuery();

	if (isPostsLoading) return <div>LOADING. . .</div>;
	if (!data) return <div>Something went wrong. . .</div>;

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					{!isSignedIn ? <SignInButton /> : <SignOutButton />}
					{isSignedIn && <>{user.firstName}</>}
				</div>
				<div>
					{data.map((post) => (
						<div key={post.id}>{post.content}</div>
					))}
				</div>
			</main>
		</>
	);
};

export default Home;
